apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-mc
  labels:
    app: profile-mc
spec:
  selector:
    matchLabels:
      app: profile-mc
  replicas: 1
  template:
    metadata:
      labels:
        app: profile-mc
    spec:
      containers:
      - name: promc
        image: memcached
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: profile-mc
spec:
  ports:
  - port: 11211
    targetPort: 11211
    protocol: TCP
  selector:
    app: profile-mc 
  type: ClusterIP
